[build-system]
requires = ["setuptools>=68.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sentier_vocab"
authors = [
  { name="Chris Mutel", email="chris@d-d-s.ch" }
]
maintainers = [
  { name="Chris Mutel", email="chris@d-d-s.ch" }
]
description = "The data processing scripts and configuration to build the DdS vocabulary"
readme = "README.md"
dynamic = ["version"]
# Add here all kinds of additional classifiers as defined under
# https://pypi.org/classifiers/
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering"
]
requires-python = ">=3.10"
dependencies = [
    "loguru",
    "platformdirs",
    "rdflib",
    "requests",
    "rfc3987",
    "skosify",
    "tqdm",
]

[project.urls]
source = "https://github.com/sentier-dev/sentier_vocab"
homepage = "https://github.com/sentier-dev/sentier_vocab"
tracker = "https://github.com/sentier-dev/sentier_vocab/issues"

[project.optional-dependencies]
# Getting recursive dependencies to work is a pain, this
# seems to work, at least for now
testing = [
    "sentier_vocab",
    "pytest",
    "pytest-cov",
    "python-coveralls"
]
dev = [
    "build",
    "pre-commit",
    "pylint",
    "pytest",
    "pytest-cov",
    "pytest-randomly",
    "setuptools",
]

[tool.setuptools]
license-files = ["LICENSE"]
include-package-data = true
packages = ["sentier_vocab"]

[tool.setuptools.dynamic]
version = {attr = "sentier_vocab.__version__"}

[tool.pytest.ini_options]
addopts = "--cov sentier_vocab --cov-report term-missing --verbose"
norecursedirs = [
    "dist",
    "build",
    ".tox"
]
testpaths = ["tests/*.py"]

[tool.flake8]
# Some sane defaults for the code style checker flake8
max_line_length = 100
extend_ignore = ["E203", "W503"]
# ^  Black-compatible
#    E203 and W503 have edge cases handled by black
exclude = [
    ".tox",
    "build",
    "dist",
    ".eggs",
    "docs/conf.py",
]

[tool.black]
line-length = 100

[tool.isort]
profile = "black"
line_length = 100
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
