"""Generate the living coverage matrix (docs/COVERAGE.md) from the ILCD catalog."""

from dataclasses import dataclass
from pathlib import Path

from sentier_vocab import iris
from sentier_vocab.paths import DATA_DIR


@dataclass(frozen=True)
class DataType:
    name: str
    namespace: str
    status: str
    source_layer: str
    folder: str | None
    notes: str


# ILCD / ISO 14040-44 reference taxonomy. `namespace` values must exist in iris.NAMESPACES.
CATALOG: list[DataType] = [
    DataType(
        "Elementary flows",
        iris.NAMESPACES["flows"],
        "🟡 partial",
        "importer + native",
        "elementary-flows",
        "ENVO water subset; native curation underway",
    ),
    DataType(
        "Flow properties",
        iris.NAMESPACES["flow-properties"],
        "❌ missing",
        "native",
        "flow-properties",
        "New schema + data",
    ),
    DataType(
        "Units / unit groups",
        iris.NAMESPACES["units"],
        "🟡 partial",
        "importer",
        None,
        "QUDT units imported; no group model yet (transitional)",
    ),
    DataType(
        "Products",
        iris.NAMESPACES["products"],
        "🟡 partial",
        "both",
        "products",
        "Some native products; formalize schema",
    ),
    DataType(
        "Processes",
        iris.NAMESPACES["processes"],
        "❌ missing",
        "native",
        "processes",
        "New schema + data",
    ),
    DataType(
        "LCIA methods",
        iris.NAMESPACES["lcia-methods"],
        "❌ missing",
        "native (+ Phase-2 import)",
        "lcia-methods",
        "AGB/BAFU import planned",
    ),
    DataType(
        "Impact categories",
        iris.NAMESPACES["impact-categories"],
        "❌ missing",
        "native",
        "impact-categories",
        "New schema + data",
    ),
    DataType(
        "Characterization factors",
        iris.NAMESPACES["characterization-factors"],
        "❌ missing",
        "native (+ Phase-2 import)",
        "characterization-factors",
        "Links flow ↔ impact category",
    ),
    DataType(
        "Model terms",
        iris.NAMESPACES["model-terms"],
        "✅ native",
        "native",
        "model-terms",
        "Formalize schema",
    ),
    DataType(
        "Sources",
        iris.NAMESPACES["sources"],
        "❌ missing",
        "native",
        "sources",
        "Bibliographic references",
    ),
    DataType(
        "Contacts",
        iris.NAMESPACES["contacts"],
        "❌ missing",
        "native",
        "contacts",
        "Data providers / contacts",
    ),
]


def count_terms(folder: str | None) -> int:
    """Count native term YAML files in a category folder (0 if folder absent/None)."""
    if not folder:
        return 0
    directory = DATA_DIR / folder
    if not directory.exists():
        return 0
    return len(list(directory.glob("*.yaml")))


def render(catalog: list[DataType] = CATALOG) -> str:
    """Render the coverage matrix as Markdown."""
    lines = [
        "# Sentier.dev Vocabulary Coverage",
        "",
        "Generated by `app/sentier_vocab/coverage.py`. ILCD / ISO 14040-44 reference taxonomy.",
        "",
        "| Data type | IRI namespace | Status | Source layer | Native files | Notes |",
        "|---|---|---|---|---|---|",
    ]
    for dt in catalog:
        lines.append(
            f"| {dt.name} | `{dt.namespace}` | {dt.status} | {dt.source_layer} "
            f"| {count_terms(dt.folder)} | {dt.notes} |"
        )
    return "\n".join(lines) + "\n"


def write(path: Path | str) -> Path:
    """Write the rendered matrix to a file. Returns the path."""
    path = Path(path)
    path.write_text(render())
    return path
